
Directory Structure

    app
    - The app directory holds the base code for your Laravel application.
    bootstrap
    - The bootstrap directory holds all the bootstrapping scripts used for your application.
    config
    - The config directory holds all your project configuration files (.config).
    database
    - The database directory holds your database files.
    assets
    - The assets directory holds your system assets files like css, JavaScript, images, etc.
    public
    - The public directory helps in starting your Laravel project and also holds other scripts (JavaScript and CSS) as well along with images required for your project.
    resources
    - The resources directory holds all the Sass files, language (localization) files, templates (if any).
    routes
    - The routes directory hold all your definition files for routing such as console.php, api.php, channels.php etc.
    storage
    - The storage directory holds your session files, cache, compiled templates as well as miscellaneous files generated by the framework.
    uploads
    - The uploads directory hold all uploaded images on system like customer images, logo, media files, etc
    test
    - The test directory holds all your test cases.
    vendor
    - The vendor directory holds all composer dependency files.

